greeting = "Hello from bar.py..."
farewell = "Goodbye from bar.py..."
i_love_python = "I love Python from bar.py..."
hotfix = "This will cause a merge conflict..."
doing_something = "Doing something in bar.py..."
