name: Cut a release

on:
  workflow_dispatch:
    inputs:
      release-type:
        name: Release type
        type: choice
        options: 
          - major
          - minor
        default: minor

jobs:
  cut-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    name: Cut ${{ github.event.inputs.release-type }} release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          ref: dev

      - name: Cut and tag release branch
        id: cut-release-branch
        run: |
          rc_version=$(scripts/cut-release.sh ${{ github.event.inputs.release-type }} release)
          echo "version=$(scripts/bump-version.sh minor $rc_version)" >> $GITHUB_OUTPUT

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: gh pr create -B master -H release --title 'Release ${{ steps.cut-release-branch.outputs.version }}' --body 'Auto-generated by `cut-release` workflow.'
