name: Cut a release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        options: 
          - major
          - minor
        default: minor

jobs:
  cut-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    name: Cut ${{ github.event.inputs.release-type }} release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create release branch
        id: cut-release-branch
        run: |
          rc_version=$(scripts/cut-release.sh ${{ github.event.inputs.release-type }} release)
          echo "rc_version=$rc_version" >> $GITHUB_OUTPUT
          echo "version=$(scripts/bump-version.sh minor $rc_version)" >> $GITHUB_OUTPUT
        
      - name: Checkout release
        uses: actions/checkout@v4
        with:
          ref: release
          token: ${{ secrets.MY_TOKEN }}

      - name: Tag release
        run: |
          git tag ${{ steps.cut-release-branch.outputs.rc_version }}
          git push origin ${{ steps.cut-release-branch.outputs.rc_version }}

      - name: Publish release
        uses: ./.github/workflows/publish-release.yaml
        with:
          version: ${{ steps.cut-release-branch.outputs.rc_version }}
          target-branch: release
        secrets:
          pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}


      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: gh pr create -B master -H release --title 'Release ${{ steps.cut-release-branch.outputs.version }}' --body 'Auto-generated by `cut-release` workflow.'
