name: Cut a release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        options: 
          - major
          - minor
        default: minor

jobs:
  cut-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    name: Cut ${{ github.event.inputs.release-type }} release

    outputs:
      rc-version: ${{ steps.cut-release-branch.outputs.rc-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create release branch
        id: cut-release-branch
        run: |
          rc-version=$(scripts/cut-release.sh ${{ github.event.inputs.release-type }} release)
          echo "rc-version=$rc-version" >> $GITHUB_OUTPUT
          echo "version=$(scripts/bump-version.sh minor $rc-version)" >> $GITHUB_OUTPUT
        
      - name: Checkout release
        uses: actions/checkout@v4
        with:
          ref: release
          token: ${{ secrets.MY_TOKEN }}

      - name: Tag release
        run: |
          git tag ${{ steps.cut-release-branch.outputs.rc-version }}
          git push origin ${{ steps.cut-release-branch.outputs.rc-version }}

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: gh pr create -B master -H release --title 'Release ${{ steps.cut-release-branch.outputs.version }}' --body 'Auto-generated by `cut-release` workflow.'

  publish-release:
    name: Publish release
    needs: cut-release
    uses: ./.github/workflows/publish-release.yaml
    with:
      target-branch: release
      version: ${{ needs.cut-release.outputs.rc-version }}
    secrets:
      pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
    permissions:
      contents: write
      id-token: write
