name: Cut a release

on:
  workflow_dispatch:
    inputs:
      release-type:
        name: Release type
        type: choice
        options: 
          - major
          - minor
        default: minor

jobs:
  cut-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    name: Cut ${{ github.event.inputs.release-type }} release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate reference branch
        if: github.ref_name != github.event.repository.default_branch
        run: |
          echo "ERROR: Release branch must be cut from default branch."
          exit 1

      - name: Cut release branch
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git fetch --unshallow
          git checkout dev
          git pull
          git checkout -b release
          git push --set-upstream origin release

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: gh pr create -B master -H release --title '${{ github.event.inputs.release-type }} release' --body 'Auto-generated by `cut-release` workflow'
