name: Sync push to master

on:
  push:
    branches:
      - master

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  sync-dev:
    name: Merge master into dev
    needs: checkout
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge master into dev
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merged master into dev"
          git push

  sync-release:
    name: Merge master into release
    needs: checkout
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge master into release
        if: github.ref != 'release'
        run: |
          if git show-ref --quiet refs/heads/release; then
          git checkout release
          git pull
          git merge --no-ff master -m "Auto-merged master into release"
          git push
          else
          echo "Release branch not found, skipping."
          fi
