name: Sync

on:
  pull_request:
    branches:
      - master
      - release
    types:
      - closed

jobs:
  tag-version:
    name: Tag version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Determine version segment to bump
        run: |
          case ${{ github.base_ref }} in
            master)
              case ${{ github.head_ref }} in
                release)
                  echo "version-segment=minor" >> $GITHUB_ENV
                  ;;
                *)
                  echo "version-segment=patch" >> $GITHUB_ENV
                  ;;
              esac
              ;;
            release)
              echo "version-segment=patch" >> $GITHUB_ENV
              ;;
            *)
              echo "Error: Unsupported base branch ${{ github.base_ref }}" >&2
              exit 1
              ;;
          esac

      - name: Create tag
        run: |
          git fetch --unshallow
          version=$(git describe --tags --abbrev=0)
          new_version=$(scripts/bump-version.sh ${{ env.version-segment }} $version)
          echo "Bumping $version to $new_version"
          git tag $new_version
          git push origin $new_version

  sync-dev:
    name: Merge ${{ github.base_ref }} into dev
    needs: tag-version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          url=$(gh pr create -B dev -H ${{ github.base_ref }} --title 'Sync with ${{ github.base_ref }}' --body 'Auto-generated by `sync` workflow.')
          gh pr merge $url --auto --merge

  sync-release:
    name: Merge ${{ github.base_ref }} into release
    needs: tag-version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          if git show-ref --quiet refs/heads/release; then
          url=$(gh pr create -B release -H ${{ github.base_ref }} --title 'Sync with ${{ github.base_ref }}' --body 'Auto-generated by `sync` workflow.')
          gh pr merge $url --auto --merge
          else
          echo "Release branch not found, skipping."
          fi
