on:
  push:
    branches:
      - master
      - release
    tags-ignore:
      - '**'

jobs:
  tag-stable-version:
    name: Tag version
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          VERSION=$(git tag -l "v*" | head -n 1)
          git tag $VERSION
          git push origin $VERSION
  
  tag-prerelease-version:
    name: Tag version
    runs-on: ubuntu-latest
    if: github.base_ref == 'release'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag $(make version)
          git push origin $(make version)
